language: c++

os:
  - linux

dist: bionic
sudo: false

before_install:
  - sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev libglew-dev
    
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2